version: "2"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      NEO_SEEDS: "http://api.otcgo.cn:20332;https://seed1.neo.org:20331;http://seed2.neo.org:20332;http://seed3.neo.org:20332;http://seed4.neo.org:20332;https://test1.cityofzion.io;https://test2.cityofzion.io;https://test3.cityofzion.io;https://test4.cityofzion.io;https://test5.cityofzion.io;http://seed5.neo.org:20332"

  phoenix:
    container_name: "phoenixdev"
    image: bitwalker/alpine-elixir-phoenix:1.7.3
    command: sh -c "while true; do echo Alive; sleep 100; done"
    volumes:
      - ./:/data
    ports:
      - 4000:4000
