version: "2"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  phoenix:
    container_name: "phoenixdev"
    image: bitwalker/alpine-elixir-phoenix:1.7.3
    command: sh -c "while true; do echo Alive; sleep 100; done"
    volumes:
      - ./:/data
    ports:
      - 4000:4000

